#!/bin/bash

DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
BRANCH=$(git branch --show-current)
MERGE_BASE=$(git merge-base $DEFAULT_BRANCH $BRANCH)

git diff $MERGE_BASE
