#!/bin/bash

FILES=$($G2_INSTALL/g2-files)
while IFS= read -r line; do
  if [ -f $line ]; then
    SCM="<<<"
    if grep -q "$SCM<$SCM" $line; then
       echo "File contains SCM change markers:"
       echo $line
       exit 1
    fi
    SCM=">>>"
    if grep -q "$SCM>$SCM" $line; then
       echo "File contains SCM change markers:"
       echo $line
       exit 1
    fi
  fi
done <<< "$FILES"

$G2_INSTALL/g2-commit
