#!/bin/bash

DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
BRANCH=$(git branch --show-current)

# Snapshot first
$G2_INSTALL/g2-snapshot
if [ $? -ne 0 ]; then
  echo "Snapshot failed"
  exit 1
fi

git fetch -q origin $DEFAULT_BRANCH:$DEFAULT_BRANCH
if [ $? -ne 0 ]; then
  exit 1
fi

git merge $DEFAULT_BRANCH

